const items=[
['instrument','Vokal mikrofonu'],['instrument','Elektro gitar'],['instrument','Akustik gitar'],['instrument','Bas gitar'],['instrument','Davul seti'],['instrument','Darbuka'],['instrument','Bendir'],['instrument','Bağlama'],['instrument','Keman'],['instrument','Viyola'],['instrument','Çello'],['instrument','Kontrbas'],['instrument','Klavye'],['instrument','Piyano'],['instrument','Akordeon'],['instrument','Saksafon'],['instrument','Trompet'],['instrument','Trombon'],['instrument','Klarnet'],['instrument','Ney'],['instrument','Ud'],['instrument','Kanun'],['instrument','Kemençe'],['instrument','Zurna'],['instrument','DJ Setup'],
['pa','Line Array L'],['pa','Line Array R'],['pa','2×18” Subwoofer L'],['pa','2×18” Subwoofer R'],['pa','1×18” Monitor Sub L'],['pa','1×18” Monitor Sub R'],['pa','Sahne Monitörü'],['pa','IEM / PSM'],['pa','Front Fill'],['pa','Delay Speaker'],['pa','Mikrofon Standı'],['pa','DI Box'],['pa','Drum Mikrofon Seti'],['pa','Stagebox'],['pa','Power / Distro'],['pa','Kablo Hattı'],
['console','Midas M32'],['console','Behringer X32'],['console','Yamaha CL5'],['console','Allen & Heath Avantis'],['console','Digital Stagebox'],['console','Monitor World'],['console','FOH Konsol'],
['stage','Truss 2 m'],['stage','Truss 3 m'],['stage','Truss Tower'],['stage','Riser'],['stage','Drum Riser'],['stage','Bariyer'],['stage','Sahne Merdiveni'],['stage','Backdrop'],['stage','Konuşmacı Kürsüsü'],['stage','Flight Case'],
['light','Moving Head'],['light','LED Par'],['light','Followspot'],['light','LED Wall'],['light','Strobe'],['light','Blinder'],['light','Işık Konsolu'],['light','Kamera'],['light','Video Kontrol'],
['production','FOH'],['production','Backstage'],['production','Monitor Pozisyonu'],['production','Acil Çıkış'],['production','Yangın Söndürücü'],['production','WC / Kabin'],['production','Depo / Malzeme'],['production','Güvenlik'],['production','Seyirci Alanı']
];
const categoryLabels={instrument:'Enstrüman',pa:'PA / Ses',console:'Konsol',stage:'Sahne',light:'Işık / Video',production:'Prodüksiyon'};
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function svgIcon(name){const C='viewBox="0 0 64 64" aria-hidden="true" focusable="false"';const S=b=>`<svg ${C} class="equipment-svg" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">${b}</svg>`;
if(name.includes('Mikrofon')||name==='Vokal mikrofonu'||name==='Konuşmacı Kürsüsü')return S('<rect x="25" y="8" width="14" height="32" rx="7"/><path d="M20 30c0 9 5 15 12 15s12-6 12-15M32 45v11M24 56h16"/>');
if(name.includes('gitar'))return S('<path d="M13 43c7-2 10-6 9-12-1-6 3-10 9-10 5 0 9 3 9 8 0 4 2 6 6 7l5-6 4 4-7 8c-3 3-7 2-11 0-4-2-7 0-10 4l-6 7-10-10z"/><path d="M38 22L57 6M43 27L61 12"/>');
if(['Keman','Viyola','Çello','Kontrbas','Kemençe'].includes(name))return S('<path d="M25 9c7 2 8 8 4 13-2 3-2 5 1 9 4 5 3 10-1 14-6 6-15 3-17-3-2-5 2-9 5-12 2-3 2-5-1-9-3-4 0-10 9-12z"/><path d="M31 11l29 48M27 15l31 44M23 19l30 40"/>');
if(['Klavye','Piyano'].includes(name))return S('<rect x="7" y="18" width="50" height="34" rx="3"/><path d="M14 18v34M21 18v34M28 18v34M35 18v34M42 18v34M49 18v34M10 42h44"/><path d="M18 18v16M30 18v16M42 18v16M50 18v16"/>');
if(['Davul seti','Darbuka','Bendir','Drum Mikrofon Seti'].includes(name))return S('<ellipse cx="32" cy="34" rx="18" ry="13"/><circle cx="12" cy="27" r="8"/><circle cx="52" cy="27" r="8"/><path d="M18 20L10 8M46 20l8-12M24 47l-5 11M40 47l5 11"/>');
if(['Saksafon','Trompet','Trombon','Klarnet','Ney','Zurna'].includes(name))return S('<path d="M39 8c-2 12-8 18-15 23-6 5-5 14 2 16 9 3 17-4 17-13"/><path d="M40 9h13v6H41M24 31l-8-7"/><circle cx="29" cy="37" r="2"/><circle cx="34" cy="33" r="2"/>');
if(['Ud','Kanun','Bağlama'].includes(name))return S('<path d="M32 8c14 0 23 10 20 22-2 9-8 17-20 24-12-7-18-15-20-24C9 18 18 8 32 8z"/><circle cx="32" cy="34" r="6"/><path d="M32 28V5M28 29L25 7M36 29l3-22"/>');
if(name==='DJ Setup')return S('<rect x="6" y="16" width="52" height="38" rx="4"/><circle cx="19" cy="35" r="11"/><circle cx="45" cy="35" r="11"/><circle cx="19" cy="35" r="4"/><circle cx="45" cy="35" r="4"/><path d="M28 23h8M28 30h8M28 37h8M28 44h8"/>');
if(name.includes('Line Array'))return S('<rect x="18" y="7" width="28" height="50" rx="3"/><path d="M22 15h20M22 25h20M22 35h20M22 45h20"/><path d="M46 15l10 6-10 6M46 31l10 6-10 6M46 47l10 6"/>');
if(name.includes('Subwoofer'))return S('<rect x="8" y="7" width="48" height="51" rx="3"/><circle cx="23" cy="24" r="10"/><circle cx="41" cy="43" r="10"/><circle cx="23" cy="24" r="4"/><circle cx="41" cy="43" r="4"/>');
if(name==='Sahne Monitörü')return S('<path d="M8 45l5-27h38l5 27H8z"/><path d="M18 25h28M15 34h34"/>');
if(name==='IEM / PSM')return S('<path d="M20 14c-6 0-10 5-10 11v10c0 6 4 10 10 10M44 14c6 0 10 5 10 11v10c0 6-4 10-10 10M20 25c3-4 7-6 12-6s9 2 12 6M20 38c3 4 7 6 12 6s9-2 12-6"/>');
if(['Midas M32','Behringer X32','Yamaha CL5','Allen & Heath Avantis','FOH Konsol'].includes(name))return S('<path d="M7 14h50l-5 42H12L7 14z"/><rect x="15" y="19" width="34" height="11" rx="2"/><path d="M14 37h36M14 46h36"/><circle cx="21" cy="41" r="2"/><circle cx="32" cy="41" r="2"/><circle cx="43" cy="41" r="2"/>');
if(['Digital Stagebox','Stagebox'].includes(name))return S('<rect x="9" y="8" width="46" height="49" rx="4"/><path d="M16 17h32M16 27h32M16 37h32M16 47h32"/><circle cx="21" cy="22" r="2"/><circle cx="32" cy="22" r="2"/><circle cx="43" cy="22" r="2"/>');
if(name==='Monitor World')return S('<rect x="7" y="10" width="50" height="44" rx="4"/><rect x="13" y="16" width="38" height="12" rx="2"/><path d="M14 38h36M14 46h36"/><circle cx="21" cy="42" r="3"/><circle cx="34" cy="42" r="3"/><circle cx="47" cy="42" r="3"/>');
if(name.includes('Truss'))return S('<rect x="12" y="9" width="40" height="46"/><path d="M12 9l40 46M52 9L12 55M12 21h40M12 33h40M12 45h40"/>');
if(['Riser','Drum Riser','Backdrop'].includes(name))return S('<path d="M8 44h48L50 22H14L8 44z"/><path d="M14 22l-4-10h44l-4 10"/>');
if(['Moving Head','LED Par','Followspot','Strobe','Blinder'].includes(name))return S('<path d="M18 50h28l-4-8H22l-4 8z"/><rect x="21" y="14" width="22" height="27" rx="6"/><circle cx="32" cy="27" r="8"/><path d="M26 14l-5-7M38 14l5-7"/>');
if(['LED Wall','Video Kontrol'].includes(name))return S('<rect x="7" y="10" width="50" height="38" rx="2"/><path d="M14 17h8v8h-8zM28 17h8v8h-8zM42 17h8v8h-8zM14 31h8v8h-8zM28 31h8v8h-8zM42 31h8v8h-8z"/><path d="M24 54h16"/>');
if(name==='Işık Konsolu')return S('<path d="M8 17h48l-5 38H13L8 17z"/><rect x="15" y="22" width="34" height="9"/><path d="M14 39h36M14 47h36"/><circle cx="21" cy="43" r="2"/><circle cx="32" cy="43" r="2"/><circle cx="43" cy="43" r="2"/>');
if(name==='Kamera')return S('<rect x="10" y="21" width="36" height="25" rx="4"/><path d="M46 27l11-6v25l-11-6z"/><circle cx="27" cy="33" r="8"/>');
if(['FOH','Backstage','Monitor Pozisyonu','Acil Çıkış','Yangın Söndürücü','WC / Kabin','Depo / Malzeme','Güvenlik','Seyirci Alanı'].includes(name))return S('<circle cx="32" cy="32" r="22"/><path d="M20 32h24M32 20v24"/>');
return S('<rect x="10" y="10" width="44" height="44" rx="6"/><path d="M18 32h28M32 18v28"/>');}
const $=id=>document.querySelector(id);const lib=$('#library'),stage=$('#stage');let filter='all',drag=null,objects=[],selected=null,zoom=1;
function iconMarkup(x){return `<div class="icon icon-${x[0]}">${svgIcon(x[1])}</div>`}
function renderLib(){const q=$('#search').value.toLocaleLowerCase('tr-TR');lib.innerHTML='';items.filter(x=>(filter==='all'||x[0]===filter)&&x[1].toLocaleLowerCase('tr-TR').includes(q)).forEach(x=>{const d=document.createElement('div');d.className='item';d.draggable=true;d.innerHTML=`${iconMarkup(x)}<div class="meta">${esc(x[1])}<small>${categoryLabels[x[0]]}</small></div>`;d.addEventListener('dragstart',e=>{drag=x;e.dataTransfer.effectAllowed='copy'});d.addEventListener('dblclick',()=>addObject(x,120,120));lib.appendChild(d)})}
function addObject(x,left=100,top=100,img=null){const o={id:crypto.randomUUID(),cat:x[0],name:x[1],x:left,y:top,r:0,w:90,h:60,img,z:objects.length};objects.push(o);draw(o);selectObject(o.id)}
function draw(o){const old=stage.querySelector(`[data-id="${o.id}"]`);if(old)old.remove();const el=document.createElement('div');el.className='obj'+(selected===o.id?' selected':'');el.dataset.id=o.id;el.style.cssText=`left:${o.x}px;top:${o.y}px;width:${o.w}px;height:${o.h}px;transform:rotate(${o.r}deg);z-index:${o.z??1}`;el.innerHTML=o.img?`<img src="${o.img}"><div>${esc(o.name)}</div>`:`<div class="obj-icon">${svgIcon(o.name)}</div><div>${esc(o.name)}</div>`;const del=document.createElement('span');del.className='del';del.textContent='×';del.onclick=e=>{e.stopPropagation();deleteObject(o.id)};const rot=document.createElement('span');rot.className='rot';rot.textContent='↻';rot.onclick=e=>{e.stopPropagation();o.r=(o.r+15)%360;draw(o);selectObject(o.id)};const resize=document.createElement('span');resize.className='resize';resize.textContent='↗';resize.onpointerdown=e=>{e.stopPropagation();e.preventDefault();const sx=e.clientX,sy=e.clientY,sw=o.w,sh=o.h;resize.setPointerCapture(e.pointerId);resize.onpointermove=a=>{o.w=Math.max(50,sw+a.clientX-sx);o.h=Math.max(36,sh+a.clientY-sy);draw(o);selectObject(o.id)}};el.append(del,rot,resize);el.addEventListener('pointerdown',e=>{if(e.target===del||e.target===rot||e.target===resize)return;selectObject(o.id);el.setPointerCapture(e.pointerId);const sx=e.clientX,sy=e.clientY,ox=o.x,oy=o.y;const move=a=>{let nx=ox+(a.clientX-sx)/zoom,ny=oy+(a.clientY-sy)/zoom;if($('#snap').checked){nx=Math.round(nx/20)*20;ny=Math.round(ny/20)*20}o.x=Math.max(0,Math.min(stage.clientWidth-o.w,nx));o.y=Math.max(0,Math.min(stage.clientHeight-o.h,ny));el.style.left=o.x+'px';el.style.top=o.y+'px';syncProps()};const up=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',up)});el.ondblclick=()=>{o.r=(o.r+15)%360;draw(o);selectObject(o.id)};stage.appendChild(el)}
function selectObject(id){selected=id;stage.querySelectorAll('.obj').forEach(e=>e.classList.toggle('selected',e.dataset.id===id));const o=objects.find(v=>v.id===id);$('#selectionEmpty').hidden=!!o;$('#selectionPanel').hidden=!o;if(o)syncProps()}
function syncProps(){const o=objects.find(v=>v.id===selected);if(!o)return;$('#propName').value=o.name;$('#propX').value=(o.x/100).toFixed(1);$('#propY').value=(o.y/100).toFixed(1);$('#propR').value=o.r;$('#propW').value=(o.w/100).toFixed(1);$('#propH').value=(o.h/100).toFixed(1)}
function updateSelected(){const o=objects.find(v=>v.id===selected);if(!o)return;o.name=$('#propName').value||o.name;o.x=Math.max(0,Number($('#propX').value)*100);o.y=Math.max(0,Number($('#propY').value)*100);o.r=Number($('#propR').value)||0;o.w=Math.max(50,Number($('#propW').value)*100);o.h=Math.max(36,Number($('#propH').value)*100);draw(o);selectObject(o.id)}
function deleteObject(id){objects=objects.filter(v=>v.id!==id);stage.querySelector(`[data-id="${id}"]`)?.remove();if(selected===id)selectObject(null)}function clearStage(){objects=[];selected=null;stage.querySelectorAll('.obj').forEach(e=>e.remove());selectObject(null)}
function projectData(){return{version:3,app:'StagePulse Plot',project:{name:$('#projectName').value,note:$('#projectNote').value,width:Number($('#stageW').value),depth:Number($('#stageD').value)},objects}}
function save(){localStorage.stagepulsePlot=JSON.stringify(projectData());alert('Plot cihazda kaydedildi.')}
function load(data){clearStage();const p=data.project||{};$('#projectName').value=p.name||'Stage Plot';$('#projectNote').value=p.note||'';$('#stageW').value=p.width||10;$('#stageD').value=p.depth||8;(data.objects||[]).forEach(o=>{objects.push(o);draw(o)});selectObject(objects[0]?.id||null)}
function exportJSON(){const b=new Blob([JSON.stringify(projectData(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=(($('#projectName').value||'stage-plot').replace(/[^a-z0-9çğıöşü_-]+/gi,'-'))+'.json';a.click();URL.revokeObjectURL(a.href)}
function setZoom(v){zoom=Math.max(.5,Math.min(2,v));stage.style.transform=`scale(${zoom})`;stage.style.width=(100/zoom)+'%';stage.style.height=(100/zoom)+'%';$('#zoomValue').textContent=Math.round(zoom*100)+'%'}
stage.onclick=e=>{if(e.target===stage)selectObject(null)};stage.ondragover=e=>e.preventDefault();stage.ondrop=e=>{e.preventDefault();if(!drag)return;const r=stage.getBoundingClientRect();addObject(drag,Math.max(0,(e.clientX-r.left)/zoom),Math.max(0,(e.clientY-r.top)/zoom));drag=null};
$('#search').oninput=renderLib;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.cat;renderLib()});$('#grid').onchange=e=>stage.classList.toggle('grid',e.target.checked);$('#clearBtn').onclick=clearStage;$('#newBtn').onclick=()=>{clearStage();$('#projectName').value='Stage Plot';$('#projectNote').value=''};$('#saveBtn').onclick=save;$('#exportBtn').onclick=exportJSON;$('#printBtn').onclick=()=>window.print();$('#zoomIn').onclick=()=>setZoom(zoom+.1);$('#zoomOut').onclick=()=>setZoom(zoom-.1);$('#fitBtn').onclick=()=>setZoom(1);
['propName','propX','propY','propR','propW','propH'].forEach(id=>$(id).addEventListener('change',updateSelected));$('#deleteBtn').onclick=()=>selected&&deleteObject(selected);$('#duplicateBtn').onclick=()=>{const o=objects.find(v=>v.id===selected);if(o){const n={...o,id:crypto.randomUUID(),x:o.x+30,y:o.y+30,z:objects.length};objects.push(n);draw(n);selectObject(n.id)}};$('#frontBtn').onclick=()=>{const o=objects.find(v=>v.id===selected);if(o){o.z=999;draw(o);selectObject(o.id)}};$('#backBtn').onclick=()=>{const o=objects.find(v=>v.id===selected);if(o){o.z=0;draw(o);selectObject(o.id)}};
$('#imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>addObject(['stage','Özel Görsel'],120,120,reader.result);reader.readAsDataURL(f)};$('#loadBtn').onclick=()=>$('#fileLoad').click();$('#fileLoad').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{load(JSON.parse(r.result))}catch{alert('Geçersiz Plot JSON dosyası.')}};r.readAsText(f)};
try{const saved=JSON.parse(localStorage.stagepulsePlot||'null');if(saved)load(saved)}catch{}renderLib();setZoom(1);