const items=(window.StagePulseEquipmentCatalog?.items||[]).map(x=>({...x,ratio:x.w/x.h}));
const labels={instrument:'Enstrüman',pa:'PA / Ses',console:'Konsol',stage:'Sahne',light:'Işık / Video',production:'Prodüksiyon'};
const $=id=>document.getElementById(id);const lib=$('library'),stage=$('stage');let filter='all',drag=null,objects=[],selected=null,zoom=1,lockRatio=false,S=80;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function renderLib(){if(!lib)return;const q=($('search')?.value||'').toLocaleLowerCase('tr-TR');lib.innerHTML='';items.filter(x=>(filter==='all'||x.cat===filter)&&x.name.toLocaleLowerCase('tr-TR').includes(q)).forEach(x=>{const d=document.createElement('div');d.className='item';d.draggable=true;d.innerHTML=`<div class="icon photo-icon"><img src="${esc(x.img)}" alt="${esc(x.name)}"></div><div class="meta">${esc(x.name)}<small>${labels[x.cat]||x.cat}</small><small>${x.w} × ${x.h} m</small></div>`;d.ondragstart=()=>drag=x;d.ondblclick=()=>addObject(x,120,120);lib.appendChild(d)})}
function addObject(x,left=100,top=100){const o={id:crypto.randomUUID(),...x,x:left,y:top,r:0,z:objects.length};objects.push(o);draw(o);selectObject(o.id);save()}
function draw(o){const old=stage?.querySelector(`[data-id="${o.id}"]`);if(old)old.remove();if(!stage)return;const e=document.createElement('div');e.className='obj'+(selected===o.id?' selected':'');e.dataset.id=o.id;e.style.cssText=`left:${o.x}px;top:${o.y}px;width:${Math.max(45,o.w*S*zoom)}px;height:${Math.max(38,o.h*S*zoom)}px;transform:rotate(${o.r}deg);z-index:${o.z??1}`;e.innerHTML=`<div class="obj-icon"><img src="${esc(o.img)}" alt="${esc(o.name)}"></div><div class="obj-label">${esc(o.name)}</div>`;
const del=document.createElement('span');del.className='del';del.textContent='×';del.onclick=a=>{a.stopPropagation();deleteObject(o.id)};
const rot=document.createElement('span');rot.className='rot';rot.textContent='↻';rot.onclick=a=>{a.stopPropagation();o.r=(o.r+15)%360;draw(o);selectObject(o.id);save()};
const rs=document.createElement('span');rs.className='resize';rs.textContent='↗';rs.onpointerdown=a=>{a.stopPropagation();a.preventDefault();const sx=a.clientX,sy=a.clientY,sw=o.w,sh=o.h;rs.setPointerCapture(a.pointerId);const mv=b=>{o.w=Math.max(.1,sw+(b.clientX-sx)/(S*zoom));o.h=lockRatio?o.w/(o.ratio||1):Math.max(.1,sh+(b.clientY-sy)/(S*zoom));draw(o);selectObject(o.id)};const up=()=>{rs.removeEventListener('pointermove',mv);rs.removeEventListener('pointerup',up);save()};rs.addEventListener('pointermove',mv);rs.addEventListener('pointerup',up)};
e.append(del,rot,rs);e.onpointerdown=a=>{if([del,rot,rs].includes(a.target))return;selectObject(o.id);e.setPointerCapture(a.pointerId);const sx=a.clientX,sy=a.clientY,ox=o.x,oy=o.y;const mv=b=>{o.x=Math.max(0,ox+(b.clientX-sx)/zoom);o.y=Math.max(0,oy+(b.clientY-sy)/zoom);e.style.left=o.x+'px';e.style.top=o.y+'px';syncProps()};const up=()=>{e.removeEventListener('pointermove',mv);e.removeEventListener('pointerup',up);save()};e.addEventListener('pointermove',mv);e.addEventListener('pointerup',up)};stage.appendChild(e)}
function getObj(){return objects.find(o=>o.id===selected)}function selectObject(id){selected=id;objects.forEach(o=>stage?.querySelector(`[data-id="${o.id}"]`)?.classList.toggle('selected',o.id===id));syncProps()}
function syncProps(){const o=getObj(),e=$('selectionEmpty'),p=$('selectionPanel');if(!o){if(e)e.hidden=false;if(p)p.hidden=true;return}e.hidden=true;p.hidden=false;$('propName').value=o.name;$('propX').value=(o.x/S).toFixed(2);$('propY').value=(o.y/S).toFixed(2);$('propR').value=o.r;$('propW').value=o.w.toFixed(2);$('propH').value=o.h.toFixed(2)}
function props(){const o=getObj();if(!o)return;o.name=$('propName').value;o.x=Math.max(0,Number($('propX').value||0)*S);o.y=Math.max(0,Number($('propY').value||0)*S);o.r=Number($('propR').value||0);o.w=Math.max(.1,Number($('propW').value||o.w));o.h=Math.max(.1,Number($('propH').value||o.h));if(lockRatio)o.h=o.w/(o.ratio||1);draw(o);syncProps();save()}
function deleteObject(id){objects=objects.filter(o=>o.id!==id);stage?.querySelector(`[data-id="${id}"]`)?.remove();selected=null;syncProps();save()}
function clearStage(){objects=[];selected=null;stage?.querySelectorAll('.obj').forEach(e=>e.remove());syncProps();save()}
function updateStage(){if(!stage)return;stage.style.width=Math.max(320,Number($('stageW')?.value||10)*S)+'px';stage.style.height=Math.max(240,Number($('stageD')?.value||8)*S)+'px';objects.forEach(draw)}
function setZoom(v){zoom=Math.min(1.6,Math.max(.5,v));if($('zoomValue'))$('zoomValue').textContent=Math.round(zoom*100)+'%';objects.forEach(draw);syncProps()}
function save(){try{localStorage.setItem('stagepulsePlot',JSON.stringify({objects,projectName:$('projectName')?.value||'',projectNote:$('projectNote')?.value||''}))}catch(_){} }
function load(){try{const d=JSON.parse(localStorage.getItem('stagepulsePlot')||'null');objects=Array.isArray(d?.objects)?d.objects:[];objects.forEach(o=>{o.w=Number(o.w)||.5;o.h=Number(o.h)||.5;o.ratio=o.ratio||o.w/o.h});objects.forEach(draw);syncProps()}catch(_){clearStage()}}
function duplicate(){const o=getObj();if(!o)return;const n={...o,id:crypto.randomUUID(),x:o.x+30,y:o.y+30,z:objects.length};objects.push(n);draw(n);selectObject(n.id);save()}
function bringFront(){const o=getObj();if(o){o.z=Math.max(...objects.map(x=>x.z??0),0)+1;draw(o);save()}}
function sendBack(){const o=getObj();if(o){o.z=0;objects.filter(x=>x!==o).forEach(x=>x.z=(x.z??0)+1);objects.forEach(draw);save()}}
if(stage){stage.addEventListener('dragover',e=>e.preventDefault());stage.addEventListener('drop',e=>{e.preventDefault();if(!drag)return;const r=stage.getBoundingClientRect();addObject(drag,(e.clientX-r.left)/zoom,(e.clientY-r.top)/zoom);drag=null})}
$('clearBtn')?.addEventListener('click',clearStage);$('newBtn')?.addEventListener('click',clearStage);$('saveBtn')?.addEventListener('click',save);$('printBtn')?.addEventListener('click',()=>window.print());$('zoomOut')?.addEventListener('click',()=>setZoom(zoom-.1));$('zoomIn')?.addEventListener('click',()=>setZoom(zoom+.1));$('fitBtn')?.addEventListener('click',()=>setZoom(1));$('stageW')?.addEventListener('input',updateStage);$('stageD')?.addEventListener('input',updateStage);$('duplicateBtn')?.addEventListener('click',duplicate);$('frontBtn')?.addEventListener('click',bringFront);$('backBtn')?.addEventListener('click',sendBack);$('deleteBtn')?.addEventListener('click',()=>selected&&deleteObject(selected));['propName','propX','propY','propR','propW','propH'].forEach(id=>$(id)?.addEventListener('input',props));document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.cat||'all';renderLib()}));$('search')?.addEventListener('input',renderLib);renderLib();updateStage();load();window.clearStage=clearStage;
