window.StagePulseEquipmentCatalog={version:8,items:[
{cat:'console',name:'Midas M32',img:'https://cdn-media.empowertribe.com/2ec241f460b6433b93fbf6a39abf319a/Image_MI_0603-ADX_M32_Front_XL.png',w:1.55,h:.85},
{cat:'console',name:'Allen & Heath Avantis',img:'https://shop.ccisolutions.com/StoreFront/jsp/images/categories/ANH.JPG',w:1.30,h:.65,blend:'multiply'},
{cat:'console',name:'Yamaha M7CL',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Yamaha_M7CL_digital_live-sound_mixing_console_-_left_half_angled.jpg',w:1.30,h:.65},
{cat:'console',name:'Yamaha CL5',img:'https://www.nicepng.com/png/detail/392-3923618_yamaha-cl5-yamaha-cl5-digital-mixing-console.png',w:1.30,h:.52},
{cat:'console',name:'Yamaha DM7',img:'https://www.prolighting.de/de/tontechnik/mischpult/digitalmischpulte/yamaha-dm7-digital-mixing-console.html',w:1.30,h:.70,blend:'multiply'},
{cat:'console',name:'DiGiCo SD9',img:'https://images.squarespace-cdn.com/content/v1/6615269f96189162f570f21d/1715615320072-0NC1QMQGC06NVBZDAH82/0022_Digico-SD9-Front.jpg?format=1000w',w:1.30,h:.85,blend:'multiply'},
{cat:'instrument',name:'Elektro Gitar',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/E-Gitarre.png',w:.38,h:1.05},
{cat:'instrument',name:'Fender Telecaster',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Fender_72_Telecaster_Thinline.png',w:.38,h:1.10},
{cat:'instrument',name:'Yamaha 5 Telli Bass',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Baixo_yamahax.PNG',w:.32,h:1.05},
{cat:'instrument',name:'Yamaha RBX 200 Bass',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Yamaha_bass_guitar_RBX_200.jpg',w:.65,h:.90},
{cat:'instrument',name:'Yamaha Keyboard',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/YamahaKeyboard.jpg',w:1.35,h:.45},
{cat:'instrument',name:'Roland Jupiter-8',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Roland_Jupiter-8_Synth%2C_1983_%28transparent_bg_no_shadow%29.png',w:1.30,h:.45},
{cat:'instrument',name:'Klasik Gitar',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Guitar_on_transparent_background.png',w:1.05,h:.42},
{cat:'instrument',name:'Akustik / Elektro Gitar',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Electric_Guitar_%28Superstrat_based_on_ESP_KH_-_vertical%29.png',w:.40,h:1.05},
{cat:'pa',name:'Shure SM57',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Shure_SM57.png',w:.08,h:.30},
{cat:'pa',name:'AKG C214',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/AKG_C214_Condenser_microphone.png',w:.10,h:.34},
{cat:'pa',name:'Shure PSM300',img:'https://www.pngkey.com/png/detail/608-6088655_shure-psm-300-twin-pack-band-g20-aed.png',w:.55,h:.30},
{cat:'pa',name:'Behringer P2',img:'https://cdn-media.empowertribe.com/242b61f813674fe6ac558c7015ed4cf0/Image_BE_0609-AAJ_P2_Front_XL.png',w:.10,h:.16},
{cat:'stage',name:'Mikrofon Sehpası',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Outside_mic_01.png',w:.35,h:.75}
]};